name = "CaenProcessing"
uuid = "7e9d5953-169b-4535-8b62-5626c83d9d85"
authors = ["kcarloni <kcarloni@g.harvard.edu>", "thomwg11 <thomwg11@gmail.com>"]
version = "0.1.0"

[deps]
AstroParticleUnits = "7ef70e66-125c-4f32-8552-6b4d78ac8c93"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"

[sources]
AstroParticleUnits = {url = "https://github.com/kcarloni/AstroParticleUnits.jl.git"}